# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Bot',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
