# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20171128_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bot_mark',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
